# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version: 3

blocks:

  - type: prompt
    alignment: left
    segments:

      - type: session
        foreground: lightGreen
        template: "{{ .UserName }}<default>@</>{{ .HostName }}"

      - type: git
        foreground: lightRed
        properties:
          fetch_status: true
        template: " <default>::</> {{ .HEAD }}{{ if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String}}{{ end }}"

  - type: prompt
    alignment: right
    segments:

      - type: shell
        foreground: lightBlue
        template: "<default>in</> {{ .Name }}"

      - type: time
        foreground: lightBlue
        properties:
          time_format: 15:04
        template: " <default>at</> {{ .CurrentDate | date .Format }} "

  - type: prompt
    alignment: left
    newline: true
    segments:

      - type: python
        foreground: lightYellow
        properties:
          home_enabled: true
        template: "({{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Major }}.{{ .Minor }}{{ end }}) "

      - type: path
        foreground: cyan
        foreground_templates:
          - "{{ if not .Writable }}darkGray{{ end }}"
        template: "{{ .Path }} "
        properties:
          style: powerlevel
          max_width: 88  # if the path is longer, the parent names will get shortened

      - type: text
        foreground: green
        foreground_templates:
          - "{{ if gt .Code 0 }}red{{ end }}"
        template: "➜ "
